---------------------------------------------------
-- Sheet: BCD to gray
-- RefDes: PLD1
-- Part Number: XC3S500E
-- Generated By: Multisim
--
-- Author: Akshat
-- Date: Thursday, October 17 08:41:00, 2019
---------------------------------------------------

---------------------------------------------------
-- Use: This file contains definitions of components
-- Use with the exported top-level file
---------------------------------------------------
library ieee;
use ieee.std_logic_1164.ALL;
use ieee.numeric_std.ALL;

package BCD_to_Gray_pkg is

	component AUTO_IBUF
		port(
		I : in std_logic;
		O : out std_logic
	);
	end component;

	component AUTO_OBUF
		port(
		I : in std_logic;
		O : out std_logic
	);
	end component;

	component XOR2_NI
		port (
    B : in STD_LOGIC := 'X';
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
	end component;

end BCD_to_Gray_pkg;
package body BCD_to_Gray_pkg is
end BCD_to_Gray_pkg;


library work;
use work.BCD_to_Gray_pkg.ALL;
library IEEE;
use IEEE.STD_LOGIC_1164.all;

entity AUTO_IBUF is
	port(
		I : in std_logic;
		O : out std_logic
	);end AUTO_IBUF;

architecture AUTO_IBUF_ARCH of AUTO_IBUF is

begin
 O <= I;
end AUTO_IBUF_ARCH;


library work;
use work.BCD_to_Gray_pkg.ALL;
library IEEE;
use IEEE.STD_LOGIC_1164.all;

entity AUTO_OBUF is
	port(
		I : in std_logic;
		O : out std_logic
	);end AUTO_OBUF;

architecture AUTO_OBUF_ARCH of AUTO_OBUF is

begin
 O <= I;
end AUTO_OBUF_ARCH;


library work;
use work.BCD_to_Gray_pkg.ALL;
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity XOR2_NI is
  port (
    B : in STD_LOGIC := 'X';
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
end XOR2_NI;

architecture BEHAVIORAL of XOR2_NI is  

begin
  Y <= A xor B;
end BEHAVIORAL;
