---------------------------------------------------
-- Sheet: SISO
-- RefDes: PLD1
-- Part Number: XC3S500E
-- Generated By: Multisim
--
-- Author: Akshat
-- Date: Thursday, October 17 09:22:21, 2019
---------------------------------------------------

---------------------------------------------------
-- Use: This file defines the top-level of the design
-- Use with the exported package file
---------------------------------------------------
library ieee;
use ieee.std_logic_1164.ALL;
use ieee.numeric_std.ALL;

library work;
use work.HDL_SISO_pkg.ALL;


entity SISO is
	port (

		SW0 : in std_logic;
		SW1 : in std_logic;
		LED0 : out std_logic;
		LED1 : out std_logic;
		LED2 : out std_logic;
		LED3 : out std_logic;
		sys_clk_pin : in std_logic
	);
end SISO;


architecture behavioral of SISO is


	component AUTO_IBUF
		port(
		I : in std_logic;
		O : out std_logic
	);
	end component;

	component AUTO_OBUF
		port(
		I : in std_logic;
		O : out std_logic
	);
	end component;

	component FF_D_CO_NI
		Port ( D : in  STD_LOGIC;
           CLK : in  STD_LOGIC;
           Q : out  STD_LOGIC;
           Qneg : out  STD_LOGIC);
	end component;
	signal \1\ : std_logic;
	signal \6\ : std_logic;
	signal \5\ : std_logic;
	signal \4\ : std_logic;
	signal \2\ : std_logic;
	signal \3\ : std_logic;
begin
	SW0_AUTOBUF : AUTO_IBUF
		port map( I => SW0, O => \5\ );
	SW1_AUTOBUF : AUTO_IBUF
		port map( I => SW1, O => \6\ );
	LED0_AUTOBUF : AUTO_OBUF
		port map( I => \1\, O => LED0 );
	LED1_AUTOBUF : AUTO_OBUF
		port map( I => \2\, O => LED1 );
	LED2_AUTOBUF : AUTO_OBUF
		port map( I => \3\, O => LED2 );
	LED3_AUTOBUF : AUTO_OBUF
		port map( I => \4\, O => LED3 );
	U2 : FF_D_CO_NI
		port map( D => \5\, Q => \1\, CLK => \6\, Qneg => open );
	U3 : FF_D_CO_NI
		port map( D => \1\, Q => \2\, CLK => \6\, Qneg => open );
	U4 : FF_D_CO_NI
		port map( D => \2\, Q => \3\, CLK => \6\, Qneg => open );
	U5 : FF_D_CO_NI
		port map( D => \3\, Q => \4\, CLK => \6\, Qneg => open );
end behavioral;
