---------------------------------------------------
-- Sheet: D_ff
-- RefDes: PLD1
-- Part Number: XC3S500E
-- Generated By: Multisim
--
-- Author: Akshat
-- Date: Thursday, October 17 09:05:48, 2019
---------------------------------------------------

---------------------------------------------------
-- Use: This file defines the top-level of the design
-- Use with the exported package file
---------------------------------------------------
library ieee;
use ieee.std_logic_1164.ALL;
use ieee.numeric_std.ALL;

library work;
use work.D_FF_pkg.ALL;


entity D_ff is
	port (

		SW0 : in std_logic;
		SW1 : in std_logic;
		LED0 : out std_logic;
		sys_clk_pin : in std_logic
	);
end D_ff;


architecture behavioral of D_ff is


	component AUTO_IBUF
		port(
		I : in std_logic;
		O : out std_logic
	);
	end component;

	component AUTO_OBUF
		port(
		I : in std_logic;
		O : out std_logic
	);
	end component;

	component FF_D_CO_NI
		Port ( D : in  STD_LOGIC;
           CLK : in  STD_LOGIC;
           Q : out  STD_LOGIC;
           Qneg : out  STD_LOGIC);
	end component;
	signal \1\ : std_logic;
	signal \3\ : std_logic;
	signal \2\ : std_logic;
begin
	SW0_AUTOBUF : AUTO_IBUF
		port map( I => SW0, O => \2\ );
	SW1_AUTOBUF : AUTO_IBUF
		port map( I => SW1, O => \3\ );
	LED0_AUTOBUF : AUTO_OBUF
		port map( I => \1\, O => LED0 );
	U2 : FF_D_CO_NI
		port map( D => \2\, Q => \1\, CLK => \3\, Qneg => open );
end behavioral;
